Feat/add matomo language button tracking
technologiestiftung/giessdenkiez-de pull request #700
Opened 2024-02-16 15:41 UTC by aeschi

we also need to change NEXT_PUBLIC_MATOMO_URL in .env

https://app.asana.com/0/1204152181784036/1206612990757854

2024-02-16 15:52 UTC, aeschi commented
I changed .env for staging accordingly

2024-02-16 16:19 UTC, raphael-arce approved these changes
one suggestion otherwise lgtm 👍  thx

2024-02-16 16:19 UTC, raphael-arce commented on src/components/Switch/matomo.ts
let's move this file in a more global folder. maybe in the `utils` folder 👍

2024-02-16 16:20 UTC, raphael-arce commented
@aeschi @ff6347 @Jaszkowic should we test this in some manner?

2024-02-16 16:45 UTC, aeschi commented on src/components/Switch/matomo.ts
done!

2024-02-17 06:29 UTC, ff6347 commented
But how? Intercept the request with MSW could be one solution.

2024-02-19 06:54 UTC, ff6347 requested changes
Great you made this work with Matomo. Good job.

My 50cent on the structure:

- Should a type declaration on the global window object be buried in a utils file? Shouldn't we introduce something like `src/common/globals.d.ts` or `src/common/window.d.ts` for things like this?
- Also file in `/util` holds a function that is solely used in one other location. The `Switch/index.tsx` Shouldn't it be located there instead of introducing a new utils file with one single not reused function?
- The type of `any[]` is only there to shut Typescript up. If you want TS to shut up a `//@ts-ignore` is enough. If you want type safety us `unknown` and do some defensive programming please.

2024-02-19 08:15 UTC, raphael-arce commented
@ff6347 I‘m joining the discussion as I pair-programmed with @aeschi to implement this. 

1. yes, that‘s a valid point.
2. while this function is only used once atm, we expect it to be used more often in the future to track specific events (e.g. tracking on salespage outlink), that‘s why I suggested to move it in a more global folder. Would you still prefer to have moved while there is only a single usage?
3. valid point as well!

regarding the testing, i agree, we should use something like msw. However, I researched a bit and found this feature from playwright: https://playwright.dev/docs/mock 

especially the HAR files feature seem interesting to mock the analytics script from matomo. What do you think?

2024-02-19 08:22 UTC, ff6347 commented
> @ff6347 I‘m joining the discussion as I pair-programmed with @aeschi to implement this.
 
> 2. while this function is only used once atm, we expect it to be used more often in the future to track specific events (e.g. tracking on salespage outlink), that‘s why I suggested to move it in a more global folder. Would you still prefer to have moved while there is only a single usage?

I guess _when_ we start using this in other locations we still can refactor the code base to move it into another shared file. Having 3 lines of code in a file just in case somewhere in the future we might reuse it, is (IMHO), over engineering.


> regarding the testing, i agree, we should use something like msw. However, I researched a bit and found this feature from playwright: https://playwright.dev/docs/mock
> 
> especially the HAR files feature seems interesting to mock the analytics script from matomo. What do you think?

If we plan to use playwright for more e2e tests I would say let's go for playwright. We already have msw in the code base I would not introduce another dep just for testing this one feature. So currently I would see if we can do this with msw first.

2024-02-19 20:01 UTC, raphael-arce commented
@ff6347 I tried to render the LandingPage via vitest and it looks like it is going to be hard to test the matomo tracking with the means we currently have:
- React Testing Library ignores script tags: 
<img width="325" alt="Bildschirmfoto 2024-02-19 um 20 16 11" src="https://github.com/technologiestiftung/giessdenkiez-de/assets/8709861/e8bdbcf8-64c4-43d9-88d2-31500a2df9fc">

- And apparently, you also cannot render the Head component from nextjs: https://github.com/testing-library/react-testing-library/issues/402#issuecomment-1013392720  (links to this discussion https://github.com/vercel/next.js/discussions/11060)
- Vitest has an experimental browser mode https://vitest.dev/guide/browser.html, I tried to use it but got an error message that vitest 1.3.0 is necessary, right now we have 1.2.1.

Maybe with more research there is a way to make it work. But probably it is going to be easier to use playwright straight away, once we decide to use it. Let's keep it in mind for the UI rework 👍

2024-03-01 09:01 UTC, ff6347 approved these changes

2024-03-01 09:20 UTC, merged