feat: add mapbox controls
technologiestiftung/giessdenkiez-de pull request #717
Opened 2024-03-07 12:41 UTC by raphael-arce

2024-03-07 12:42 UTC, raphael-arce commented on src/components/map-attribution/map-attribution.tsx
> +      pointer-events-auto absolute bottom-[4.3rem] right-1 max-w-60
@Jaszkowic I did it with absolute here bc I wasn't sure how to make it with grid. Could you help me with that?

2024-03-07 15:25 UTC, aeschi commented on src/components/map/map.tsx
> +      <div className="z-[1000] col-start-1 row-start-1 flex items-end justify-end">
this div stretches across the entire map and blocks the user from interacting with the map (no zoom, moving around etc)

2024-03-07 15:36 UTC, aeschi requested changes
- the zoom in and out works well when blending out the map attributions 👍 
- when I click on locate, I get located BUT the locate button dissapears :D

- there is currently some white space under the map making the page bigger than the window height:
<img width="1080" alt="Screenshot 2024-03-07 at 16 31 07" src="https://github.com/technologiestiftung/giessdenkiez-de/assets/56318362/bd976dcd-cbba-4511-b5b0-147686c639fd">

2024-03-14 10:45 UTC, raphael-arce commented
@aeschi I think I fixed everything, and I can't reproduce the dissapearing locate me button, could you look into it again?

2024-03-14 14:01 UTC, raphael-arce commented
@aeschi i think i fixed it now. could you please test again?

2024-03-14 14:33 UTC, aeschi approved these changes
LGTM

2024-03-14 14:36 UTC, merged