feat: splash screen
technologiestiftung/giessdenkiez-de pull request #771
Opened 2024-03-21 12:31 UTC by Jaszkowic

2024-03-21 16:34 UTC, aeschi requested changes
already looks super good!

a few comments:
- I changed the size of the language toggle earlier but it's not in this branch:
the className of the button inside LanguageToggle should be:
className="bg-gdk-white h-[51px] justify-center items-center hover:text-gdk-light-gray text-gdk-gray flex"

after changing this the padding for the language button on the splash screen on mobile should be correct

2024-03-21 16:34 UTC, aeschi commented on src/components/splash/splash.tsx
> +							<PrimaryButton label={"Los geht's"} onClick={onClose} />
internationalization missing

2024-03-21 16:34 UTC, aeschi commented on src/components/splash/splash.tsx
> +		<div className="flex flex-col gap-2">
I would add a margin mt-4 to seperate the text blocks a bit more for mobile

2024-03-21 16:34 UTC, aeschi commented on src/components/splash/splash.tsx
> +						<Markdown className="xl:text-2xl 2xl:text-3xl font-semibold">
here I would add another step for sm:text-xl

2024-03-21 16:44 UTC, Jaszkowic commented
@aeschi merged latest feat/ui-rework and fixed your suggestions

2024-03-22 08:11 UTC, aeschi approved these changes
ship it! 🚢

2024-03-22 08:45 UTC, aeschi commented
one more thing: we could exchange the <a> tags after this PR #780

2024-03-25 11:22 UTC, aeschi commented
went through these comments:

- we seem to have lost the tree icon of the logo in the new design. I'd opt for adding this back in as we're using this on https://deinestadt.giessdenkiez.de/ and in our email templates. 
- mini typo in banner for new landing page: Gieß den Kiez auch in deiner Deiner Stadt
- for EN version please use Connect for last block instead of Network
- link "Erfahre mehr" on mobile threw blank page first time around

2024-03-25 16:45 UTC, raphael-arce approved these changes
one tiny suggestion, otherwise lgtm 👍

2024-03-25 16:45 UTC, raphael-arce commented on src/components/router/router.tsx
> +	const [showSplashScreen, setShowSplashScreen] = useState(true);
could we make this `isSplashScreenVisible` ?

2024-03-25 16:51 UTC, merged